// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmbwwpjbucndwbmefgyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtYnd3cGpidWNuZHdibWVmZ3lsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMzk5MTcsImV4cCI6MjA1NzkxNTkxN30.xy9HGYr6a54QkFPtsCxAPF_ksSLc2hb7Ry4hfeKAmLU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);